[package]
name = "sl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
smithay-client-toolkit = { git = "https://github.com/Smithay/client-toolkit" }
wayland-client = "0.31.1"

