name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Insall dependencies
      run: sudo apt-get install -y libxkbcommon-dev libwayland-dev libwayland-egl-backend-dev libudev-dev libinput-dev libxcb-composite0-dev libxcb-xfixes0-dev libpam0g-dev
    - name: Build
      run: cargo build --verbose

  release:
    name: Release Simple Lock
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
