name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Insall dependencies
      run: sudo apt-get install -y libxkbcommon-dev libwayland-dev libwayland-egl-backend-dev libudev-dev libinput-dev libxcb-composite0-dev libxcb-xfixes0-dev libpam0g-dev
    - name: Build
      run: cargo build --verbose

  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: create_version
        run: ./scripts/generateVersion.sh patch >> "$GITHUB_OUTPUT"

  release:
    name: Release Simple Lock
    runs-on: ubuntu-latest
    needs: [ build, tag ]
    steps:
    - name: Get version
      id: version
      env: 
        VERSION: "${{ needs.tag.outputs.version }}"
      run: echo "version $VERSION"
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.tag.outputs.version }}
        release_name: ${{ needs.tag.outputs.version }}
        draft: false
        prerelease: false
