name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Insall dependencies
      run: sudo apt-get install -y libxkbcommon-dev libwayland-dev libwayland-egl-backend-dev libudev-dev libinput-dev libxcb-composite0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --verbose
